### ISSUE TITLE
Offline getPlayer

### ISSUE THREAD

**Issue by Acrodeminecraft** [alecgorge/jsonapi#486]
Hi, 
First I'm french so sorry if I'd make any mistake

So I use JSONAPI for Spigot 1.9.2 with the non-official version 5.7 and when I use the getPlayer call with a offline it make a bug :
[http://dzaok.tk/error.txt](url)

So I'd understood it doesn't work just I want to solve it but what decencies I need for eclipse ?
Thanks for further answers :+1:

**Comment by electronicboy** [comment]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/World
That version is compiled for 1.8.8, and isn't an official version.

The plugin also compiles cleanly with Maven without any issues for me. See the complete_build script

**Comment by Acrodeminecraft** [comment]
Thanks so it work in spigot 1.9.2 ? just how to use complete_build script ? yes I'm a noob in Eclipse but i'm good in web php / css / html ;)

**Comment by electronicboy** [comment]
The current version on git should work fine for 1.9 R1 (1.9-1.9.2)

You'll have to use the script from a bash interpreter or manually run the commands on a command line that has maven installed; Eclipse should have maven support, However I don't use eclipse so couldn't provide instructions for doing it from there, however the variables you'd need to setup are in that shell file.

**Comment by Acrodeminecraft** [comment]
I've installed maven but how to execute the script please ?

**Comment by electronicboy** [comment]
I already said, You'll need the bash interpreter to run the script. Or, Just run the mvn line from inside the script manually.

**Comment by Acrodeminecraft** [comment]
`mvn clean install $@ -DmcPackage=v1_9_R1
 -DspigotVersion=1.9-R0.1-SNAPSHOT
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.alecgorge.minecraft.jsonapi:JSONAPI:jar:BLEEDING-mc1.9-R0.1-SNAPSHOT
[WARNING] 'version' contains an expression but should be a constant. @ com.alecg
orge.minecraft.jsonapi:JSONAPI:${jsonapiVersion}-mc${spigotVersion}, C:\Users\Ga
bin\Downloads\jsonapi-master\pom.xml, line 7, column 11
[WARNING] The expression ${version} is deprecated. Please use ${project.version}
 instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version}
 instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version}
 instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version}
 instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version}
 instead.
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten t
he stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support buildin
g such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building JSONAPI BLEEDING-mc1.9-R0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.714 s
[INFO] Finished at: 2016-05-11T23:10:42+02:00
[INFO] Final Memory: 6M/46M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "$@". You must specify a valid lifecycle phase o
r a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artif
act-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, ini
tialize, generate-sources, process-sources, generate-resources, process-resource
s, compile, process-classes, generate-test-sources, process-test-sources, genera
te-test-resources, process-test-resources, test-compile, process-test-classes, t
est, prepare-package, package, pre-integration-test, integration-test, post-inte
gration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, s
ite, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhase
NotFoundException`

**Comment by Acrodeminecraft** [comment]
I've the same error with the script

**Comment by electronicboy** [comment]
Script requires a bash interpreter.
Try removing the $@ if you're not using bash.

**Comment by Acrodeminecraft** [comment]
Thanks its compiling I'm waiting the end thanks a lot
